name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from package.json
      id: extract_version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile \
        --tag shiwu077/pieces-os:${{ steps.extract_version.outputs.version }} \
        --tag shiwu077/pieces-os:latest
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push the Docker images
      run: |
        docker push shiwu077/pieces-os:${{ steps.extract_version.outputs.version }}
        docker push shiwu077/pieces-os:latest
